### PR TITLE
Refactor job.java

### PR DESCRIPTION
**Pull request by holma198**
**NOTE: ** This pull request should only be merged in after PR#3 is merged to master.  

### Summary  
**Addresses Issue [#2]**  
This PR is a supplemental PR to PR#3 (`Master` <- `Consolidate_Jobs`). This PR aims to refactor the `Job` class and clean up much of the mess made in PR#3. Changes Include:  
* Renaming fields in `Job` to reflect their actual function. (This includes changing comments that document these fields)  
* Make `Job` fields with useless setters and getters public, and remove sed setters and getters.  
* Implement field scope changes in `Job` project wide, including tests.  

Cleanup

### CODE REVIEW

**Comment by YujingSong** [comment]
This documents very organized and clear to review, commit messages explained clearly about what you did, very good document!

**Review by isaacyoa — APPROVED** [review]
The commits used were very specific and reflected a very organized pull request. Changes made to Job class are all beneficial and makes the class easier to understand.

**Review by YujingSong — APPROVED** [review]

**Review by nickplucker — COMMENTED** [review]
Your commit messages are very clear - it's easy to understand what you did to the code by just reading your commit message. The refactoring you did to `Job.java` improved the readability and got rid of unnecessary lines of code. Well done!

**Review by nickplucker — APPROVED** [review]

**Review by twarling — APPROVED** [review]
This pull request is very, very well done. The documentation and commits are clear, and I think the changes you made will make the code a lot easier to read in the future.

**Pull request merged**
